/*
 * gurumin-pad
 * Copyright (C) 2015 Daniel Bloemendal. All rights reserved.
 *
 * DirectInput device class declaration
 */

namespace proxy {
    class ProxyDirectInput8A : public IUnknown {
    public:
        ProxyDirectInput8A(IDirectInput8A* target);

        // IUnknown interface
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj);
        virtual DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef();
        virtual DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release();

        // IDirectInput8A interface
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateDevice(REFGUID rguid, LPDIRECTINPUTDEVICE8A * slplpDirectInputDevice, LPUNKNOWN pUnkOuter);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumDevices(DWORD dwDevType, LPDIENUMDEVICESCALLBACKA lpCallback, LPVOID pvRef, DWORD dwFlags);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDeviceStatus(REFGUID rguidInstance);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE RunControlPanel(HWND hwndOwner, DWORD dwFlags);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Initialize(HINSTANCE hinst, DWORD dwVersion);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE FindDevice(REFGUID rguidClass, LPCSTR ptszName, LPGUID pguidInstance);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumDevicesBySemantics(LPCSTR ptszUserName, LPDIACTIONFORMATA lpdiActionFormat, LPDIENUMDEVICESBYSEMANTICSCBA lpCallback, LPVOID pvRef, DWORD dwFlags);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ConfigureDevices(LPDICONFIGUREDEVICESCALLBACK lpdiCallback, LPDICONFIGUREDEVICESPARAMSA lpdiCDParams, DWORD dwFlags, LPVOID pvRefData);

    private:
        // Internal data
        ULONG _refs;
        IDirectInput8A* _target;
        
    };

    class ProxyDirectInputDevice8A : public IUnknown {
    public:
        ProxyDirectInputDevice8A(IDirectInputDevice8A* target);

        // IUnknown interface
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, LPVOID * ppvObj);
        virtual DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef();
        virtual DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release();

        // IDirectInputDevice8A interface
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetCapabilities(LPDIDEVCAPS);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumObjects(LPDIENUMDEVICEOBJECTSCALLBACKA, LPVOID, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetProperty(REFGUID, LPDIPROPHEADER);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetProperty(REFGUID, LPCDIPROPHEADER);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Acquire();
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Unacquire();
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDeviceState(DWORD, LPVOID);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDeviceData(DWORD, LPDIDEVICEOBJECTDATA, LPDWORD, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetDataFormat(LPCDIDATAFORMAT);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetEventNotification(HANDLE);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetObjectInfo(LPDIDEVICEOBJECTINSTANCEA, DWORD, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDeviceInfo(LPDIDEVICEINSTANCEA);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE RunControlPanel(HWND, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Initialize(HINSTANCE, DWORD, REFGUID);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateEffect(REFGUID, LPCDIEFFECT, LPDIRECTINPUTEFFECT *, LPUNKNOWN);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumEffects(LPDIENUMEFFECTSCALLBACKA, LPVOID, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetEffectInfo(LPDIEFFECTINFOA, REFGUID);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetForceFeedbackState(LPDWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SendForceFeedbackCommand(DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumCreatedEffectObjects(LPDIENUMCREATEDEFFECTOBJECTSCALLBACK, LPVOID, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Escape(LPDIEFFESCAPE);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Poll();
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SendDeviceData(DWORD, LPCDIDEVICEOBJECTDATA, LPDWORD, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumEffectsInFile(LPCSTR, LPDIENUMEFFECTSINFILECALLBACK, LPVOID, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE WriteEffectToFile(LPCSTR, DWORD, LPDIFILEEFFECT, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE BuildActionMap(LPDIACTIONFORMATA, LPCSTR, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetActionMap(LPDIACTIONFORMATA, LPCSTR, DWORD);
        virtual DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetImageInfo(LPDIDEVICEIMAGEINFOHEADERA);

    private:
        // Internal data
        ULONG _refs;
        IDirectInputDevice8A* _target;
    };
}
